version: 0.2

env:
  variables:
    IMAGE_NAME: "movie-service"
    DOCKERHUB_USERNAME: "npaulhere"
  secrets-manager:
    DOCKERHUB_PASSWORD: "arn:aws:secretsmanager:us-east-1:440744257191:secret:DOCKER_PASSWORD-o4YAlV:DOCKER_PASSWORD"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - chmod +x mvnw || true

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - echo "Fetching short commit hash..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - 'IMAGE_TAG=${COMMIT_HASH:-latest}'
      - echo "Using image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building Spring Boot application with Maven..."
      - ./mvnw clean package

      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .
      - docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images to Docker Hub..."
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
